;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cua--prefix-override-handler
	cua-paste
	mouse-set-region
	smex
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	cider-load-file
	cua-delete-region
	mouse-drag-mode-line
	python-indent-dedent-line-backspace
	))
