;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cua--prefix-override-handler
	cua-paste
	smex
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	python-indent-dedent-line-backspace
	))
